# Project: train_namespace
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../5_namespace/main.o
LINKOBJ  = ../5_namespace/main.o
LIBS     = -L"D:/devc++_an/Dev-Cpp/MinGW64/lib" -L"D:/devc++_an/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/devc++_an/Dev-Cpp/MinGW64/include" -I"D:/devc++_an/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/devc++_an/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/devc++_an/Dev-Cpp/MinGW64/include" -I"D:/devc++_an/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/devc++_an/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/devc++_an/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = train_namespace.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../5_namespace/main.o: ../5_namespace/main.cpp
	$(CPP) -c ../5_namespace/main.cpp -o ../5_namespace/main.o $(CXXFLAGS)
